name: Create Issue on First Push

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issue = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Welcome to your fork!',
            body: 'Thank you for forking this repository! Here are some things you might want to do next...'
          }
          github.issues.create(issue)
