name: Create Issue on First Push

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Check for open issues
      id: check_issues
      run: |
        ISSUES=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     https://api.github.com/repos/${{ github.repository }}/issues?state=open)
        COUNT=$(echo "$ISSUES" | jq '. | length')
        if [[ "$COUNT" -eq 0 ]]; then
          echo "::set-output name=has_issues::false"
        else
          echo "::set-output name=has_issues::true"
        fi
      continue-on-error: true

    - name: Create Issue
      if: steps.check_issues.outputs.has_issues == 'false'
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.SECRET}}
        script: |
          const issue = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Second Issue',
            body: 'Thank you for forking this repository! Here are some things you might want to do next...'
          }
          github.issues.create(issue)
